### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by andybak** [cakarsubasi/COMP491-VR-Modeller#1]
Your mesh implementation looks interesting but I can't really look at code until I know what licence it's released under. :-)

(I work on Open Brush which is Apache 2.0 licenced so I was hoping for something compatible with that)

**Comment by cakarsubasi** [comment]
Hey Andy,

I have consulted my friends whom I did this project with and have added the MIT license to it.

Keep in mind that this is a bachelor thesis project that was done within 14 weeks by 3 students. As a result, it has quite a lot of room for improvement and a lot of unfixed bugs. I wrote most of the mesh structures and as it turns out, there are a lot of gotchas involved in working with 3D model graphs. The main reason why I did the project was I was curious what it would take!

So I would just like to leave that as a word of caution when using this code, but I hope it would be interesting or helpful to you.
